"""Replace UserFlightInfo and CoachFlightInfo with unified FlightInfo

Revision ID: 624e696c0fae
Revises: 86c706dd67ba
Create Date: 2025-08-03 12:39:54.871647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '624e696c0fae'
down_revision = '86c706dd67ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('flight_departure_datetime', sa.DateTime(), nullable=True),
    sa.Column('flight_return_datetime', sa.DateTime(), nullable=True),
    sa.Column('flight_airline', sa.String(length=100), nullable=True),
    sa.Column('flight_bag_info', sa.String(length=255), nullable=True),
    sa.Column('flight_confirmation_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternate_travel', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rental_car_info', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('coach_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('coach_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('coach_phone', sa.String(length=50), nullable=True))
        batch_op.drop_column('flight_departure_datetime')
        batch_op.drop_column('flight_return_datetime')
        batch_op.drop_column('flight_bag_info')
        batch_op.drop_column('flight_confirmation_code')
        batch_op.drop_column('flight_airline')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_airline', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('flight_confirmation_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('flight_bag_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('flight_return_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('flight_departure_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('coach_phone')
        batch_op.drop_column('coach_email')
        batch_op.drop_column('coach_name')
        batch_op.drop_column('rental_car_info')
        batch_op.drop_column('alternate_travel')

    op.drop_table('flight_info')
    # ### end Alembic commands ###
