"""Add start_datetime and end_datetime to EventDay

Revision ID: 86c706dd67ba
Revises: dcd616b335e8
Create Date: 2025-08-02 12:02:45.581661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86c706dd67ba'
down_revision = 'dcd616b335e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_datetime', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_datetime', sa.DateTime(), nullable=False))
        batch_op.drop_column('day_datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('end_datetime')
        batch_op.drop_column('start_datetime')

    # ### end Alembic commands ###
