"""Add flight and accommodation info to Event

Revision ID: d23cbb83b62c
Revises: 7f38281c7136
Create Date: 2025-07-19 12:26:49.635732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23cbb83b62c'
down_revision = '7f38281c7136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_departure_datetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('flight_airline', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('flight_bag_info', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('flight_confirmation_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('accommodation_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('accommodation_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('accommodation_airbnb_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('accommodation_airbnb_link')
        batch_op.drop_column('accommodation_address')
        batch_op.drop_column('accommodation_name')
        batch_op.drop_column('flight_confirmation_code')
        batch_op.drop_column('flight_bag_info')
        batch_op.drop_column('flight_airline')
        batch_op.drop_column('flight_departure_datetime')

    # ### end Alembic commands ###
