"""Add schedule_file and bag_info fields to Event

Revision ID: dcd616b335e8
Revises: f0368f15467b
Create Date: 2025-08-01 14:51:15.410877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd616b335e8'
down_revision = 'f0368f15467b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('day_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_file', sa.String(length=255), nullable=True))
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('schedule_file')

    op.drop_table('event_days')
    # ### end Alembic commands ###
