"""Add flight return datetime and accommodation info to Event

Revision ID: f0368f15467b
Revises: d23cbb83b62c
Create Date: 2025-07-19 12:31:14.756434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0368f15467b'
down_revision = 'd23cbb83b62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flight_return_datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('flight_return_datetime')

    # ### end Alembic commands ###
